services:
  ecommerce:
    build:
      context: ./E-Commerce
      dockerfile: Dockerfile
    container_name: ecommerce_service
    ports:
      - "8000:8000"
    volumes:
      - ./E-Commerce/E-Commerce.db:/app/E-Commerce.db
      - ./order_service:/app/order_service
    environment:
      - DATABASE_URL=sqlite:///./E-Commerce.db
      - REDIS_URL=redis://redis:6379/0
      - PYTHONPATH=/app

  order_service:
    build:
      context: .
      dockerfile: ./order_service/Dockerfile
    container_name: order_service
    ports:
      - "8001:8001"
    volumes:
      - ./orders.db:/app/orders.db
    environment:
      - DATABASE_URL=sqlite:///./orders.db
      - REDIS_URL=redis://redis:6379/0

  redis:
    image: redis:7
    container_name: ecommerce_redis
    ports:
      - "6379:6379"