FROM python:3.11-slim

WORKDIR /order_service

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8001

# SQLite DB inside container
CMD ["uvicorn", "order_service.main:app", "--host", "0.0.0.0", "--port", "8001"]
