FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8001

# SQLite DB inside container
CMD ["uvicorn", "order_servicemain:app", "--host", "0.0.0.0", "--port", "8001"]