"""add customer_id to search_index

Revision ID: 4b950b70538b
Revises: d26d7b0c3c70
Create Date: 2025-09-18 11:12:40.297620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b950b70538b'
down_revision: Union[str, Sequence[str], None] = 'd26d7b0c3c70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
    op.add_column('search_index', sa.Column('customer_id', sa.Integer(), nullable=True))

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
    op.drop_column('search_index', 'customer_id')