"""add customer_id to search_index

Revision ID: d26d7b0c3c70
Revises: 5b1a57a7994a
Create Date: 2025-09-18 11:07:02.078915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd26d7b0c3c70'
down_revision: Union[str, Sequence[str], None] = '5b1a57a7994a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
